apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jarededwards/goop.git
    path: registry/clusters/mgmt/components/crossplane
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
