apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '40'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jarededwards/goop.git
    path: registry/clusters/mgmt/components/cert-manager
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
