apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://github.com/jarededwards/goop.git
    path: registry/clusters/mgmt/external-secrets-operator
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
