apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crossplane-secrets
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: mock-secret-store
    kind: ClusterSecretStore
  target:
    name: crossplane-secrets
  data:
  dataFrom:
  - extract:
      key: /crossplane
      version: v1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ci-secrets
  namespace: chartmuseum
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: mock-secret-store
    kind: ClusterSecretStore
  target:
    name: ci-secrets
  data:
  dataFrom:
  - extract:
      key: /ci-secrets
      version: v1
