apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
  namespace: atlantis
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  target:
    name: cloudflare-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: mock-secret-store
  refreshInterval: 10s
  data:
  - remoteRef:
      key: cloudflare
      property: origin-ca-api-key
    secretKey: origin-ca-api-key
---
apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: cloudflare-origin-issuer
  namespace: atlantis
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      key: origin-ca-api-key
      name: cloudflare-secrets
