apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.14.2
    chart: external-dns
    helm:
      valuesObject:
        serviceAccount:
          create: true
          name: external-dns
        provider: cloudflare
        sources:
          - ingress
        domainFilters:
          - kuberocket.com
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: external-dns-secrets
                key: token
  destination:
    name: in-cluster
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true