apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jarededwards/goop.git
    path: registry/clusters/je-kon-20/components/external-dns
    targetRevision: main
  destination:
    name: in-cluster
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true