apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  target:
    name: cloudflare-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: mock-secret-store
  refreshInterval: 10s
  data:
  - remoteRef:
      key: /cloudflare
      property: origin-ca-api-key
    secretKey: origin-ca-api-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ci-secrets
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  target:
    name: ci-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: mock-secret-store
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /ci-secrets
---
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: argo-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  target:
    name: argo-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: mock-secret-store
  refreshInterval: 10s
  data:
    - remoteRef:
        key: /oidc/argo
        property: client_id
      secretKey: client-id
    - remoteRef:
        key: /oidc/argo
        property: client_secret
      secretKey: client-secret
---
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: container-registry-auth
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  target:
    name: container-registry-auth
  secretStoreRef:
    kind: ClusterSecretStore
    name: mock-secret-store
  refreshInterval: 10s
  data:
    - remoteRef:
        key: /registry-auth
        property: auth
      secretKey: config.json
