apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.20.1
    helm:
      values: |-
        nameOverride: argo
        executor:
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1024Mi
        server:
          secure: false
          extraArgs:
          - --auth-mode=client
          - --auth-mode=sso
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/service-upstream: "true"
              cert-manager.io/issuer: cloudflare-origin-issuer
              cert-manager.io/issuer-kind: OriginIssuer
              cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            hosts:
              - argo.kubesecond.com
            paths: 
              - /
            pathType: Prefix
            tls:
              - secretName: argo-tls
                hosts:
                  - argo.kubesecond.com
          sso:
            issuer: https://vault.kubesecond.com/v1/identity/oidc/provider/kubefirst
            clientId:
              name: argo-secrets
              key: client-id
            clientSecret:
              name: argo-secrets
              key: client-secret
            redirectUrl: https://argo.kubesecond.com/oauth2/callback
            scopes:
              - email
              - openid
              - groups
              - user
              - profile
            # RBAC Config. >= v2.12
            rbac:
              enabled: true
        useDefaultArtifactRepo: true
        useStaticCredentials: true
        artifactRepository:
          archiveLogs: false
          s3:
            accessKeySecret:
              name: ci-secrets
              key: accesskey
            secretKeySecret:
              name: ci-secrets
              key: secretkey
            insecure: false
            bucket: k1-state-store-goop
            endpoint: objectstore.nyc1.civo.com
            region: nyc1
            useSDKCreds: false
            encryptionOptions:
              enableEncryption: false
    chart: argo-workflows
  destination:
    name: in-cluster
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
