apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  application.resourceTrackingMethod: annotation
  admin.enabled: 'true'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'false'
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
    tf.upbound.io/Workspace:
      health.lua: |
        local hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            local installed = false
            local healthy = false
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Ready" then
                installed = condition.status == "True"
                installed_message = condition.reason
              elseif condition.type == "Synced" then
                healthy = condition.status == "True"
                healthy_message = condition.reason
              end
            end
            if installed and healthy then
              hs.status = "Healthy"
            else
              hs.status = "Degraded"
            end
            hs.message = installed_message .. " " .. healthy_message
            return hs
          end
        end
        
        hs.status = "Progressing"
        hs.message = "Waiting for workspace to finish running"
        return hs
    apps/Deployment:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        
        if obj.status ~= nil then
          local replicas = obj.spec.replicas or 1
          local readyReplicas = obj.status.readyReplicas or 0
          local availableReplicas = obj.status.availableReplicas or 0
          
          if obj.status.conditions ~= nil then
            for i, condition in pairs(obj.status.conditions) do
              if condition.type == "Progressing" and condition.status == "True" and condition.reason == "NewReplicaSetAvailable" then
                if readyReplicas == replicas and availableReplicas == replicas then
                  hs.status = "Healthy"
                  hs.message = "Deployment is healthy"
                  return hs
                end
              end
            end
          end
          
          if readyReplicas < replicas then
            hs.status = "Progressing"
            hs.message = string.format("Waiting for deployment: %d/%d ready", readyReplicas, replicas)
          end
        end
        
        return hs
    apps/StatefulSet:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""

        if obj.status ~= nil then
          local replicas = obj.spec.replicas or 1
          local readyReplicas = obj.status.readyReplicas or 0
          local currentReplicas = obj.status.currentReplicas or 0

          if readyReplicas == replicas and currentReplicas == replicas then
            hs.status = "Healthy"
            hs.message = "StatefulSet is ready"
          else
            hs.status = "Progressing"
            hs.message = string.format("Waiting for StatefulSet: %d/%d ready", readyReplicas, replicas)
          end
        end

        return hs
