apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 7.0.0
    chart: external-dns
    helm:
      valuesObject:
        image:
          repository: registry.k8s.io/external-dns/external-dns
          tag: v0.14.0
        serviceAccount:
          create: true
          name: external-dns
        provider: cloudflare
        sources:
          - ingress
        domainFilters:
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: external-dns-secret
                key: api-token
  destination:
    name: in-cluster
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true