apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-je-kon-8
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1000"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jarededwards/goop.git
    path: registry/clusters/je-kon-8
    targetRevision: main
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
