apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: controller-manager
  namespace: github-runner
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: mock-secret-store
  target:
    name: controller-manager
  data:
    - remoteRef:
        key: /ci-secrets
        property: PERSONAL_ACCESS_TOKEN
        version: v1
      secretKey: github_token
