apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-cert-issuers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '60'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kubefirst/navigate.git
    path: registry/clusters/mgmt-cloudflare/clusters/mgmt/cert-issuers
    targetRevision: HEAD
  destination:
    name: mgmt
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
