apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: external-dns
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: external-dns
  project: default
  sources:
  - chart: external-dns
    helm:
      releaseName: external-dns
      valueFiles:
      - $values/lite/registry/clusters/goop-boop/components/external-dns/values.yaml
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.14.4
  - ref: values
    repoURL: https://github.com/jarededwards/goop.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

