serviceAccount:
  create: true
  name: external-dns
provider: cloudflare
sources:
- ingress
domainFilters:
- feedkray.com
env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: external-dns-secrets
      key: token
