apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: mgmt
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  configuration: |
      terraform {
        backend "s3" {
          bucket   = "k1-state-store-goop"
          key      = "registry/clusters/mgmt/cluster/infrastructure/terraform.tfstate"
          # key      = "env:/mgmt-infrastructure/registry/clusters/mgmt/cluster/infrastructure/terraform.tfstate"
          endpoint = "https://objectstore.nyc1.civo.com"

          region = "nyc1"

          skip_credentials_validation = true
          skip_metadata_api_check     = true
          skip_region_validation      = true
          force_path_style            = true
        }
        required_providers {
          civo = {
            source = "civo/civo"
          }
          kubernetes = {
            source = "hashicorp/kubernetes"
            version = "2.23.0"
          }
        }
      }
      provider "civo" {
        region = "nyc1"
      }
  credentials:
  - filename: gen-nothing
    source: None
    secretRef:
      namespace: crossplane-system
      name: crossplane-secrets
      key: CIVO_TOKEN
