apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
  namespace: chartmuseum
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  target:
    name: cloudflare-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: mock-secret-store
  refreshInterval: 10s
  data:
  - remoteRef:
      key: /cloudflare
      property: origin-ca-api-key
      version: v1
    secretKey: origin-ca-api-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chartmuseum-secrets
  namespace: chartmuseum
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  target:
    name: chartmuseum-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: mock-secret-store
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /chartmuseum
        version: v1
