apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chartmuseum-secrets
  namespace: chartmuseum
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  target:
    name: chartmuseum-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: mock-secret-store
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /chartmuseum
        version: v1
