apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: ingress-nginx
  project: default
  sources:
  - chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
      valueFiles:
      - $values/registry/clusters/goop-boop/components/ingress-nginx/values.yaml
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
  - ref: values
    repoURL: git@github.com:kubewhatever-com/goop.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

