apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-wait
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "41"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-dns-wait
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "41"
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-dns-wait
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "41"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-dns-wait
subjects:
  - kind: ServiceAccount
    name: external-dns-wait
    namespace: external-dns
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-external-dns
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "41"
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: external-dns-wait
      restartPolicy: OnFailure
      containers:
      - name: wait
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for all deployments in external-dns namespace to be ready..."
          kubectl wait --for=condition=available --all deployments -n external-dns --timeout=600s
          echo "All external-dns deployments are ready!"