apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  sources:
  - chart: cert-manager
    helm:
      releaseName: cert-manager
      valueFiles:
      - $values/lite/registry/clusters/goop-boop/components/cert-manager/values.yaml
    repoURL: https://charts.jetstack.io
    targetRevision: v1.15.2
  - ref: values
    repoURL: https://github.com/jarededwards/goop.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

