apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-cloudflare-origin-ca-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/cloudflare/origin-ca-issuer-charts
    chart: origin-ca-issuer
    targetRevision: 0.5.7
    helm:
      values: |-
        global:
          rbac:
            create: true
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true